// Complete list of 67 towns served by Will Shao
export const allNeighborhoodsData = [
  // Inner Suburbs
  { slug: "newton", name: "Newton", region: "Inner Suburbs", medianPrice: "$1,285,000", schools: "A+", commute: "25 min", walkScore: 72 },
  { slug: "brookline", name: "Brookline", region: "Inner Suburbs", medianPrice: "$1,120,000", schools: "A", commute: "20 min", walkScore: 85 },
  { slug: "belmont", name: "Belmont", region: "Inner Suburbs", medianPrice: "$1,050,000", schools: "A", commute: "20 min", walkScore: 70 },
  { slug: "arlington", name: "Arlington", region: "Inner Suburbs", medianPrice: "$950,000", schools: "A-", commute: "20 min", walkScore: 78 },
  { slug: "needham", name: "Needham", region: "Inner Suburbs", medianPrice: "$1,130,000", schools: "A", commute: "25 min", walkScore: 50 },
  { slug: "westwood", name: "Westwood", region: "Inner Suburbs", medianPrice: "$1,100,000", schools: "A", commute: "30 min", walkScore: 35 },
  { slug: "waltham", name: "Waltham", region: "Inner Suburbs", medianPrice: "$825,000", schools: "B+", commute: "20 min", walkScore: 65 },
  { slug: "watertown", name: "Watertown", region: "Inner Suburbs", medianPrice: "$775,000", schools: "B", commute: "15 min", walkScore: 72 },
  { slug: "dedham", name: "Dedham", region: "Inner Suburbs", medianPrice: "$765,000", schools: "B+", commute: "25 min", walkScore: 55 },
  { slug: "winchester", name: "Winchester", region: "Inner Suburbs", medianPrice: "$1,200,000", schools: "A+", commute: "25 min", walkScore: 58 },
  { slug: "medford", name: "Medford", region: "Inner Suburbs", medianPrice: "$695,000", schools: "B", commute: "20 min", walkScore: 68 },
  { slug: "somerville", name: "Somerville", region: "Inner Suburbs", medianPrice: "$825,000", schools: "B+", commute: "15 min", walkScore: 88 },
  { slug: "cambridge", name: "Cambridge", region: "Inner Suburbs", medianPrice: "$950,000", schools: "B+", commute: "10 min", walkScore: 92 },
  { slug: "brighton-allston", name: "Brighton/Allston", region: "Inner Suburbs", medianPrice: "$695,000", schools: "B", commute: "20 min", walkScore: 85 },
  { slug: "boston", name: "Boston", region: "Inner Suburbs", medianPrice: "$825,000", schools: "B+", commute: "Varies", walkScore: 90 },
  { slug: "melrose", name: "Melrose", region: "Inner Suburbs", medianPrice: "$625,000", schools: "B+", commute: "25 min", walkScore: 62 },
  { slug: "malden", name: "Malden", region: "Inner Suburbs", medianPrice: "$575,000", schools: "B", commute: "20 min", walkScore: 70 },
  { slug: "stoneham", name: "Stoneham", region: "Inner Suburbs", medianPrice: "$595,000", schools: "B", commute: "25 min", walkScore: 55 },
  { slug: "woburn", name: "Woburn", region: "Inner Suburbs", medianPrice: "$625,000", schools: "B", commute: "25 min", walkScore: 60 },
  { slug: "reading", name: "Reading", region: "Inner Suburbs", medianPrice: "$695,000", schools: "A-", commute: "30 min", walkScore: 50 },
  { slug: "north-reading", name: "North Reading", region: "Inner Suburbs", medianPrice: "$625,000", schools: "A-", commute: "35 min", walkScore: 45 },
  { slug: "wakefield", name: "Wakefield", region: "Inner Suburbs", medianPrice: "$625,000", schools: "B+", commute: "30 min", walkScore: 55 },
  { slug: "quincy", name: "Quincy", region: "Inner Suburbs", medianPrice: "$595,000", schools: "B", commute: "25 min", walkScore: 68 },
  { slug: "milton", name: "Milton", region: "Inner Suburbs", medianPrice: "$695,000", schools: "B+", commute: "25 min", walkScore: 50 },
  { slug: "braintree", name: "Braintree", region: "Inner Suburbs", medianPrice: "$575,000", schools: "B", commute: "30 min", walkScore: 55 },
  
  // MetroWest
  { slug: "wellesley", name: "Wellesley", region: "MetroWest", medianPrice: "$1,550,000", schools: "A+", commute: "30 min", walkScore: 55 },
  { slug: "natick", name: "Natick", region: "MetroWest", medianPrice: "$875,000", schools: "A", commute: "35 min", walkScore: 48 },
  { slug: "lexington", name: "Lexington", region: "MetroWest", medianPrice: "$1,350,000", schools: "A+", commute: "30 min", walkScore: 52 },
  { slug: "concord", name: "Concord", region: "MetroWest", medianPrice: "$1,420,000", schools: "A+", commute: "40 min", walkScore: 45 },
  { slug: "weston", name: "Weston", region: "MetroWest", medianPrice: "$1,450,000", schools: "A+", commute: "35 min", walkScore: 35 },
  { slug: "wayland", name: "Wayland", region: "MetroWest", medianPrice: "$985,000", schools: "A", commute: "40 min", walkScore: 30 },
  { slug: "framingham", name: "Framingham", region: "MetroWest", medianPrice: "$695,000", schools: "B+", commute: "40 min", walkScore: 52 },
  { slug: "sudbury", name: "Sudbury", region: "MetroWest", medianPrice: "$1,050,000", schools: "A+", commute: "45 min", walkScore: 22 },
  { slug: "lincoln", name: "Lincoln", region: "MetroWest", medianPrice: "$1,200,000", schools: "A+", commute: "40 min", walkScore: 28 },
  { slug: "carlisle", name: "Carlisle", region: "MetroWest", medianPrice: "$895,000", schools: "A", commute: "45 min", walkScore: 20 },
  { slug: "acton", name: "Acton", region: "MetroWest", medianPrice: "$895,000", schools: "A+", commute: "45 min", walkScore: 28 },
  { slug: "boxborough", name: "Boxborough", region: "MetroWest", medianPrice: "$925,000", schools: "A+", commute: "50 min", walkScore: 25 },
  { slug: "stow", name: "Stow", region: "MetroWest", medianPrice: "$795,000", schools: "A", commute: "50 min", walkScore: 20 },
  { slug: "hudson", name: "Hudson", region: "MetroWest", medianPrice: "$625,000", schools: "B+", commute: "50 min", walkScore: 40 },
  { slug: "marlborough", name: "Marlborough", region: "MetroWest", medianPrice: "$595,000", schools: "B", commute: "55 min", walkScore: 50 },
  { slug: "maynard", name: "Maynard", region: "MetroWest", medianPrice: "$625,000", schools: "B+", commute: "50 min", walkScore: 45 },
  { slug: "littleton", name: "Littleton", region: "MetroWest", medianPrice: "$695,000", schools: "A-", commute: "50 min", walkScore: 25 },
  { slug: "hopkinton", name: "Hopkinton", region: "MetroWest", medianPrice: "$785,000", schools: "A", commute: "50 min", walkScore: 25 },
  { slug: "ashland", name: "Ashland", region: "MetroWest", medianPrice: "$695,000", schools: "A-", commute: "45 min", walkScore: 35 },
  { slug: "sherborn", name: "Sherborn", region: "MetroWest", medianPrice: "$1,100,000", schools: "A+", commute: "40 min", walkScore: 20 },
  { slug: "medway", name: "Medway", region: "MetroWest", medianPrice: "$625,000", schools: "B+", commute: "45 min", walkScore: 30 },
  { slug: "millis", name: "Millis", region: "MetroWest", medianPrice: "$595,000", schools: "B", commute: "45 min", walkScore: 28 },
  { slug: "milford", name: "Milford", region: "MetroWest", medianPrice: "$495,000", schools: "B", commute: "50 min", walkScore: 45 },
  { slug: "southborough", name: "Southborough", region: "MetroWest", medianPrice: "$695,000", schools: "A", commute: "50 min", walkScore: 35 },
  { slug: "westborough", name: "Westborough", region: "MetroWest", medianPrice: "$625,000", schools: "B+", commute: "55 min", walkScore: 40 },
  { slug: "northborough", name: "Northborough", region: "MetroWest", medianPrice: "$625,000", schools: "B+", commute: "55 min", walkScore: 38 },
  
  // North Shore
  { slug: "andover", name: "Andover", region: "North Shore", medianPrice: "$795,000", schools: "A", commute: "45 min", walkScore: 45 },
  { slug: "north-andover", name: "North Andover", region: "North Shore", medianPrice: "$695,000", schools: "A-", commute: "50 min", walkScore: 40 },
  { slug: "lynnfield", name: "Lynnfield", region: "North Shore", medianPrice: "$625,000", schools: "A-", commute: "35 min", walkScore: 45 },
  { slug: "tewksbury", name: "Tewksbury", region: "North Shore", medianPrice: "$595,000", schools: "B+", commute: "40 min", walkScore: 50 },
  { slug: "billerica", name: "Billerica", region: "North Shore", medianPrice: "$595,000", schools: "B", commute: "40 min", walkScore: 48 },
  { slug: "westford", name: "Westford", region: "North Shore", medianPrice: "$695,000", schools: "A", commute: "45 min", walkScore: 40 },
  { slug: "chelmsford", name: "Chelmsford", region: "North Shore", medianPrice: "$625,000", schools: "A-", commute: "45 min", walkScore: 42 },
  { slug: "wilmington", name: "Wilmington", region: "North Shore", medianPrice: "$625,000", schools: "B+", commute: "35 min", walkScore: 50 },
  { slug: "bolton", name: "Bolton", region: "North Shore", medianPrice: "$595,000", schools: "B+", commute: "50 min", walkScore: 25 },
  { slug: "harvard", name: "Harvard", region: "North Shore", medianPrice: "$625,000", schools: "A-", commute: "55 min", walkScore: 20 },
  { slug: "groton", name: "Groton", region: "North Shore", medianPrice: "$595,000", schools: "A-", commute: "55 min", walkScore: 22 },
  { slug: "ayer", name: "Ayer", region: "North Shore", medianPrice: "$495,000", schools: "B", commute: "60 min", walkScore: 40 },
  { slug: "shrewsbury", name: "Shrewsbury", region: "North Shore", medianPrice: "$625,000", schools: "A-", commute: "50 min", walkScore: 45 },
  { slug: "holliston", name: "Holliston", region: "North Shore", medianPrice: "$695,000", schools: "A", commute: "45 min", walkScore: 30 },
  
  // South Shore
  { slug: "dover", name: "Dover", region: "South Shore", medianPrice: "$1,050,000", schools: "A", commute: "35 min", walkScore: 25 },
  { slug: "medfield", name: "Medfield", region: "South Shore", medianPrice: "$895,000", schools: "A", commute: "35 min", walkScore: 35 },
  { slug: "canton", name: "Canton", region: "South Shore", medianPrice: "$625,000", schools: "B+", commute: "30 min", walkScore: 45 },
  { slug: "sharon", name: "Sharon", region: "South Shore", medianPrice: "$625,000", schools: "B+", commute: "35 min", walkScore: 40 },
  { slug: "stoughton", name: "Stoughton", region: "South Shore", medianPrice: "$495,000", schools: "B", commute: "35 min", walkScore: 50 },
  { slug: "norwood", name: "Norwood", region: "South Shore", medianPrice: "$595,000", schools: "B", commute: "30 min", walkScore: 60 },
];
