/**
 * commentary.mjs — Regenerate the monthly "What This Means for You" commentary
 * in Market.tsx from the data already in that file (priceData, domData,
 * townData, and the list-to-sale key metric).
 *
 * Called by index.mjs after each scrape. Can also be run on its own:
 *   node scripts/mlspin/commentary.mjs
 */
import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

const ROOT = resolve(import.meta.dirname, '../..');
const MARKET_TSX = resolve(ROOT, 'client/src/pages/Market.tsx');

const SHORT = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const LONG  = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

const START_MARKER = '{/* COMMENTARY:START — generated by scripts/mlspin/commentary.mjs */}';
const END_MARKER   = '{/* COMMENTARY:END */}';

const SEASON = [
  'Winter is usually the quietest stretch of the year, with fewer homes listed and fewer buyers out looking.',
  'Winter is usually the quietest stretch of the year, with fewer homes listed and fewer buyers out looking.',
  'This is when the spring market starts to wake up, as more homes come on and buyers return.',
  'This is when the spring market starts to wake up, as more homes come on and buyers return.',
  "We're in the heart of the spring market, typically the busiest time of the year.",
  "We're in the heart of the spring market, typically the busiest time of the year.",
  'Summer usually stays busy, though activity starts to ease as families turn to vacations and the school year.',
  'Summer usually stays busy, though activity starts to ease as families turn to vacations and the school year.',
  'Fall typically brings a seasonal slowdown after the busy spring and summer months.',
  'Fall typically brings a seasonal slowdown after the busy spring and summer months.',
  'Activity usually slows heading into the holidays, and the buyers still looking tend to be serious ones.',
  'Activity usually slows heading into the holidays, and the buyers still looking tend to be serious ones.',
];

function parseMonth(label) {
  const m = label.match(/^(\w{3}) '(\d{2})$/);
  return { index: SHORT.indexOf(m[1]), year: 2000 + Number(m[2]), sortKey: (2000 + Number(m[2])) * 12 + SHORT.indexOf(m[1]) };
}

function parseBlock(c, name, re) {
  const block = c.match(new RegExp(`const ${name} = \\[([\\s\\S]*?)\\n\\];`));
  if (!block) throw new Error(`${name} not found in Market.tsx`);
  return [...block[1].matchAll(re)];
}

const money = (n) => `$${n.toLocaleString('en-US')}`;

function joinNames(names) {
  if (names.length <= 2) return names.join(' and ');
  return `${names.slice(0, -1).join(', ')}, and ${names[names.length - 1]}`;
}

function pctChange(cur, prev, prevName) {
  const pct = ((cur - prev) / prev) * 100;
  if (Math.abs(pct) < 1.5) return `about even with ${prevName}`;
  return `${pct < 0 ? 'down' : 'up'} ${Math.round(Math.abs(pct))}% from ${prevName}`;
}

function domChange(cur, prev, prevName) {
  if (cur === prev) return `the same as in ${prevName}`;
  return `${cur > prev ? 'up' : 'down'} from ${prev} days in ${prevName}`;
}

export function buildCommentary({ month, prev, spLp, towns }) {
  const name = LONG[month.index];
  const prevName = LONG[prev.index];
  const domTrend = month.dom - prev.dom > 1 ? 'slower' : prev.dom - month.dom > 1 ? 'faster' : 'steady';

  const overview =
    `${name} brought ${month.sales.toLocaleString('en-US')} closed sales across Greater Boston, ` +
    `${pctChange(month.sales, prev.sales, prevName)}. The median sale price came in at ${money(month.median)}, ` +
    `${pctChange(month.median, prev.median, prevName)}, and homes took an average of ${month.dom} days to sell, ` +
    `${domChange(month.dom, prev.dom, prevName)}. On average, sellers received ${spLp}% of their list price. ` +
    SEASON[month.index];

  const softest = towns.slice().sort((a, b) => a.listToSale - b.listToSale || b.dom - a.dom).slice(0, 3);
  const buyersPace = {
    slower: 'Homes are sitting a little longer than they were last month, which gives you more time to make decisions and a bit more room to negotiate.',
    faster: 'Homes are selling faster than they were last month, so it pays to be ready to act when the right one comes along.',
    steady: 'The pace of the market is holding steady from last month.',
  }[domTrend];
  const buyersRegion = spLp >= 100
    ? 'Across the region, homes are still selling at or above asking on average, so a strong first offer still matters.'
    : spLp >= 98
    ? "Across the region, most homes are still selling close to asking, so don't expect deep discounts, even in the softer towns."
    : 'Across the region, sellers are accepting a little less than asking on average, which gives prepared buyers real leverage.';
  const buyers =
    `${buyersPace} The most negotiating room right now is in ` +
    joinNames(softest.map((t) => `${t.town} (${t.listToSale}% of list, ${t.dom} days on market)`)) +
    `. ${buyersRegion}`;

  const hottest = towns.slice().sort((a, b) => b.listToSale - a.listToSale || a.dom - b.dom).slice(0, 3);
  const sellersPace = {
    slower: 'With homes taking a bit longer to sell overall, pricing your home right from day one matters more than usual. A listing that starts too high tends to sit, and buyers notice.',
    faster: 'With homes selling faster than last month, a well-prepared, well-priced listing is in a strong position.',
    steady: 'Demand is holding steady, so a well-prepared, well-priced listing remains in a strong position.',
  }[domTrend];
  const sellers =
    `${joinNames(hottest.map((t) => t.town))} are the most competitive markets we track this month, with homes ` +
    `selling at ${Math.min(...hottest.map((t) => t.listToSale))}% of list price or better. ${sellersPace}`;

  // Prefer towns not already named above so the standout adds something new.
  const named = new Set([...softest, ...hottest].map((t) => t.town));
  const pick = (sorted) => sorted.find((t) => !named.has(t.town)) ?? sorted[0];
  const fastest = pick(towns.slice().sort((a, b) => a.dom - b.dom || b.listToSale - a.listToSale));
  named.add(fastest.town);
  const slowest = pick(towns.slice().sort((a, b) => b.dom - a.dom || a.listToSale - b.listToSale));
  let standout =
    `${fastest.town} was one of the fastest-moving markets we track, with homes selling in ${fastest.dom} days on average ` +
    `at ${fastest.listToSale}% of list.`;
  if (slowest.town !== fastest.town && slowest.dom > fastest.dom) {
    standout += ` On the other end, homes in ${slowest.town} averaged ${slowest.dom} days on market, so buyers there ` +
      `have more time to weigh their options.`;
  }

  return { overview, buyers, sellers, standout };
}

export function updateCommentary() {
  let c = readFileSync(MARKET_TSX, 'utf8').replace(/\r\n/g, '\n');

  const prices = parseBlock(c, 'priceData', /\{\s*month:\s*"([^"]+)",\s*median:\s*(\d+),\s*sales:\s*(\d+)\s*\}/g)
    .map((m) => ({ label: m[1], median: Number(m[2]), sales: Number(m[3]) }));
  const doms = new Map(
    parseBlock(c, 'domData', /\{\s*month:\s*"([^"]+)",\s*dom:\s*(\d+)\s*\}/g).map((m) => [m[1], Number(m[2])])
  );
  const towns = parseBlock(c, 'townData', /\{\s*town:\s*"([^"]+)",\s*medianPrice:\s*(\d+),\s*dom:\s*(\d+),\s*listToSale:\s*([\d.]+)\s*\}/g)
    .map((m) => ({ town: m[1], medianPrice: Number(m[2]), dom: Number(m[3]), listToSale: Math.round(Number(m[4])) }));
  const spLpMatch = c.match(/\{ value: "(\d+)%", label: "List-to-Sale Ratio"/);
  if (!spLpMatch) throw new Error('List-to-Sale key metric not found in Market.tsx');

  const sorted = prices
    .map((p) => ({ ...p, ...parseMonth(p.label), dom: doms.get(p.label) }))
    .sort((a, b) => a.sortKey - b.sortKey);
  if (sorted.length < 2) throw new Error('Need at least two months of priceData to write commentary');
  const month = sorted[sorted.length - 1];
  const prev = sorted[sorted.length - 2];
  if (month.dom === undefined || prev.dom === undefined) throw new Error('domData is missing a month present in priceData');

  const { overview, buyers, sellers, standout } = buildCommentary({ month, prev, spLp: Number(spLpMatch[1]), towns });

  const indent = '              ';
  const body = [
    START_MARKER,
    `<p>\n${indent}  ${overview}\n${indent}</p>`,
    `<p>\n${indent}  <strong className="text-[#0D2137]">For Buyers:</strong> ${buyers}\n${indent}</p>`,
    `<p>\n${indent}  <strong className="text-[#0D2137]">For Sellers:</strong> ${sellers}\n${indent}</p>`,
    `<p>\n${indent}  <strong className="text-[#0D2137]">Notable Standout:</strong> ${standout}\n${indent}</p>`,
    END_MARKER,
  ].join(`\n${indent}`);

  const start = c.indexOf(START_MARKER);
  const end = c.indexOf(END_MARKER);
  if (start === -1 || end === -1) throw new Error('Commentary markers not found in Market.tsx');
  c = c.slice(0, start) + body + c.slice(end + END_MARKER.length);

  c = c.replace(/.+ — What This Means for You/, `${LONG[month.index]} ${month.year} — What This Means for You`);

  writeFileSync(MARKET_TSX, c, 'utf8');
  console.log(`  ✓ Market.tsx commentary → ${LONG[month.index]} ${month.year}`);
}

if (import.meta.url === `file://${process.argv[1]}`) updateCommentary();
